tap "homebrew/cask"
cask_args appdir: "/Applications"

# brew "git"
# brew "gh"
# brew "starship"
# brew "stow"

# cask "alfred"
# cask "android-file-transfer"
# cask "android-studio"
# cask "brave-browser"
# cask "dropbox"
# cask "flipper"
# cask "google-chrome"
# cask "iterm2"
# cask "ledger-live"
# cask "postman"
# cask "slack"
# cask "spectacle"
# cask "spotify"
# cask "steam"
# cask "surfshark"
# cask "visual-studio-code"
# cask "vysor"