#!/bin/sh

set -e

# check to see if zsh is the default shell. If not set zsh as default
if [ "$(dscl . -read ~/ UserShell)" != "UserShell: /bin/zsh" ]; then
  chsh -s /bin/zsh
  chmod -R 755 /usr/local/share/zsh
  chown -R root:staff zsh
fi

# checking brew path to see if bin file exists or not
if [ ! -f /usr/local/bin/brew ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
fi

# xcode will get prompted to install
CLONE_PATH=~/dev
if [ ! -d "$CLONE_PATH" ]; then
  mkdir -p "$CLONE_PATH"
fi

# check whether dotfiles is already cloned or not
if [ ! -d "$CLONE_PATH"/dotfiles ]; then
  cd "$CLONE_PATH"
  git clone git@github.com:elGrogz/dotfiles.git
fi

# installs all dependencies in the brewfile
brew bundle -v --file "$CLONE_PATH"/dotfiles/Brewfile

# store vscode settings directory
# VSCODE_PATH=$HOME/Library/ApplicationSupport/Code/User

# if [[ -f $VSCODE_PATH/settings.json ]]; then
#   rm $VSCODE_PATH/settings.json
# fi

# Set dotfiles/packages as the alias HOME directory and then 
stow -v -d "$CLONE_PATH"/dotfiles/packages -t $HOME zsh starship git
# stow -v -d "$CLONE_PATH"/dotfiles/packages -t $HOME/.vscode vscode